services:
  - type: web
    name: multiagent-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11